# Generated by Django 6.0.3 on 2026-03-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Receita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("tempo_preparo", models.IntegerField(help_text="Tempo em minutos")),
                ("dificuldade", models.CharField(max_length=50)),
                ("instrucoes", models.TextField()),
            ],
        ),
    ]
