# Generated by Django 6.0.3 on 2026-03-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Festival",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("localizacao", models.CharField(max_length=100)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
            ],
        ),
    ]
