# Generated by Django 6.0.3 on 2026-03-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("numero_processo", models.IntegerField(unique=True)),
                ("ano_letivo", models.CharField(max_length=20)),
            ],
        ),
    ]
